### ISSUE TITLE
Component title "Explore"

### ISSUE THREAD

**Issue by mmockett** [Financial-Times/n-storylines#23]
"Explore articles of 2014" should instead say "Explore articles from 2014—2016" (or whatever the timeframe is) on first view.

**Comment by gvonkoss** [comment]
@TheoLeanse for this to work, we need a new helper in handlebars that will find the last item in an array, _or_ add the first and last objects to another decorator (e.g. `{"span": "2014 - 2016"}` or something like that) in order to access them. 

So something along the lines of this?
```
module.exports = function timeSpan (data) {
	const addTimeSpan = () => {
		const span = `${data.children[0]} — ${data.children[data.children.length-1]`;
		return Object.assign({}, { span });
	};

	const clone = Object.assign({}, data);
	clone(addTimeSpan)

	return clone;
};

```
I suppose that means that if there will have to be another conditional in the template, but if we have that extra object, I'll sort it out.

**Comment by gvonkoss** [comment]
https://github.com/Financial-Times/n-storylines/releases/tag/v0.6.3
